### ISSUE TITLE
Création de turmites - Enoncé

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/PLM#312]
Lors de l'initialisation de rule, l'énoncé nous demande de mettre RIGHT pour effectuer 
le dessin proposé. Mais pour crée le vrai dessin, il faut remplacer RIGHT par LEFT...

--------------------[ Informations techniques ]--------------------
Lesson: turmites
Exercise: turmites.lessons.turmites.turmitecreator.TurmiteCreator
Programming Language: Scala
Locale: français (France)
Java version: 1.7.0_67 (VM: Java HotSpot(TM) Client VM; version: 24.65-b04)
OS: Windows 8.1 (version: 6.3; arch: x86)
PLM version: 2.4.4 (20140912)
Public user ID: PLM0ac65182d526af67d39200bd4b4f2ddaa4e853ee

**Comment by mquinson** [comment]
This is a duplicate of #468, thus closing.
