### ISSUE TITLE
Student code should be run in a separate JVM

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/PLM#379]
When we put " exit" on the code, the PLM closes itself. It's quiet aggressive...

--------------------[ Informations techniques ]--------------------

Lesson: recursion
Exercise: recursion.lessons.recursion.spiral.SpiralUse
Programming Language: Scala
Locale: français (France)
Java version: 1.8.0_05 (VM: Java HotSpot(TM) 64-Bit Server VM; version: 25.5-b02)
OS: Linux (version: 3.13.0-35-generic; arch: amd64)
PLM version: 2.4.10 (20140930)
Public user ID: PLMa4009bd6149be52625131e81f89c14ece93b8439

**Comment by mquinson** [comment]
Just for the record, this is currently implemented in https://github.com/BuggleInc/PLM-judge

**Comment by mquinson** [comment]
This is now implemented in production in the web version, thus closing.
