### ISSUE TITLE
Transitionning the github repo

### ISSUE THREAD

**Issue by mquinson** [BuggleInc/PLM#404]
We were speaking of transitionning from github.com/oster/PLM to something like github.com/Buggles/PLM or something.

I think that this transition should be done in a smooth manner :
- Make sure that PLM can use either address, trying one after the other. We have to deal with the user code on PLM-data, bugs and feedback on PLM and the interactions on PLM-servers (calling for help and such)
- Release a version of PLM able of dealing with both addresses
- (wait a week for the new version to get distributed)
- Actually do the switch

Woot, that's the issue 404 for a 404 problem :)

**Comment by jcb** [comment]
You could create an organization, then change the ownership of the project (and add the contributors to the organization). It could be a solution.

**Comment by polux** [comment]
Might come in handy: https://github.com/google/github-issue-mover

**Comment by polux** [comment]
Hmm, only works for individual issues, not sure that's tractable.

**Comment by mquinson** [comment]
On Fri, May 29, 2015 at 12:32:31AM -0700, jcb wrote:
> You could create an organization, then change the ownership of the project (and add the contributors to the organization). It could be a solution.

That's what we had in mind.  The main difficulty is to pick an
organisation name :) If you have a proposition, please go ahead.

Mt

**Comment by mquinson** [comment]
On Fri, May 29, 2015 at 12:39:06AM -0700, Paul Brauner wrote:
> Might come in handy: https://github.com/google/github-issue-mover

Actually, we wanted to change the ownership of the project so that's
less relevant. But thanks for sharing the link anyway, I think it will
help when we merge repos webPLM and PLM... Thanks.

**Comment by jcb** [comment]
Which kind of name are you expecting? (PLM -centered or something wider — and therefore more generic). I throw here few ideas to bootstrap the brainstorming:
- Buggle Associates
- The Buggle Consortium
- PLM Associates
- Computer Science Learning Group / CSLG / CS Learning Group (more generic, could be reused for CSIRL/SMN projects)
- GASI (French version of the previous idea :))
- LYPGG (Learn You Prog for Great Good!), a reference to LYHGG (Learn You a Haskel for Great Good!)
- …

**Comment by mquinson** [comment]
I like Buggle Associates. We could use it for CSIRL/ SMN project, provided that we start using space invaders in these activities. I mean, why not ;)

**Comment by mquinson** [comment]
We should just avoid Buggle Corps that I was liking first, because of https://en.wikipedia.org/wiki/Drum_and_bugle_corps_%28modern%29

**Comment by mquinson** [comment]
I just created BuggleInc. I created BuggleAssociates at first, but it was too long and rendered as BuggleAssoci.../PLM on the interface. That's still better than BuggleAss.../PLM but I decided to switch anyway. 

We can continue with the switching process. It's particularly important for the issues and PLM-data

**Comment by mquinson** [comment]
Everything is now moved into the BuggleInc organization. In particular, GitHub provides eternal redirections (as long as no other repo of the same name is created), so we don't have to bother about it. 

Thus closing the bug.
