### ISSUE TITLE
Expected results are apparently not the most efficient

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/PLM#414]
I successfully completed the second bubble sort test (Performance test set) with 90 fewer read operations than expected - I can't pass the test because I did it better than the program expected. I'm not sure where I missed those 90 read operations, but my array is correctly sorted.

--------------------[ Technical Information ]--------------------
(This can help us fixing your problem, please don't erase)

Lesson: sort.basic
Exercise: sort.basic.lessons.sort.basic.bubble.AlgBubbleSort2
World: Functional test [2, 1, 8, 3, 4, 5, 6, 7, 0, 9]
World: Performance test (150 elms) [104, 1, 7, 6, 41, 80, 3, 54, 8, 37, 10, 28, 66, 13, 14, 128, 47, 17, 18, 107, 79, 21, 73, 23, 24, 5, 26, 27, 146, 2, 30, 31, 131, 33, 34, 120, 0, 135, 38, 129, 53, 44, 4, 89, 93, 109, 61, 46, 48, 139, 50, 51, 126, 92, 111, 103, 102, 57, 88, 59, 35, 56, 62, 121, 86, 65, 142, 143, 71, 69, 70, 68, 72, 22, 74, 20, 87, 75, 32, 76, 16, 115, 100, 83, 84, 82, 132, 97, 58, 43, 127, 119, 113, 145, 94, 95, 99, 77, 98, 118, 85, 130, 25, 11, 12, 67, 106, 39, 133, 136, 110, 81, 124, 134, 114, 29, 116, 117, 60, 55, 96, 63, 122, 123, 36, 141, 52, 112, 78, 149, 138, 15, 64, 140, 45, 148, 40, 137, 147, 19, 108, 125, 90, 105, 144, 42, 91, 101, 9, 49]
Programming Language: Java
Locale: English (United States)
Java version: 1.7.0_65 (VM: OpenJDK 64-Bit Server VM; version: 24.65-b04)
OS: Linux (version: 3.13.0-37-generic; arch: amd64)
PLM version: 2.5 (20141031)
Public user ID: PLM5dd50de5d70cb83126db59a9a8a9c5e0258d8678

**Comment by mquinson** [comment]
As you did not insist on requesting that this fact is made bolder in the text, I'm closing this report. Thanks for using the PLM.
