### ISSUE TITLE
When sending feedback, the url of the generated issue must be clickable

### ISSUE THREAD

**Issue by DamienCassou** [BuggleInc/PLM#429]
I've just sent feedback from the application and got a message box with the url of the generated issue on PLM's issue tracker. But the link is not clickable making it hard to visit the generated issue (for, e.g., subscribing to it).

**Comment by mquinson** [comment]
Hello,

Thanks for your feedback, I fixed the typo. We won't fix this one as we are currently rewriting the whole interface as a web application. The distributed jarfile will be a webserver, and the interface will be in the browser. You can test it here: https://github.com/MatthieuNICOLAS/webPLM 

We will fix that bug when the feedback reporting feature will be implemented in webPLM.

Thanks,

**Comment by MatthieuNICOLAS** [comment]
The feedback reporting feature is now live in webPLM (since https://github.com/BuggleInc/webPLM/commit/ebe0c8dea9bdd1b92c9ba0180f48f69750512063) and the link of the generated issue is clickable.

Thus closing this issue.
