### ISSUE TITLE
Le rouge sur rouge c'est pas la joie

### ISSUE THREAD

**Issue by mquinson** [BuggleInc/PLM#466]
_From @Minious on September 4, 2015 13:53_

Le premier exo de la catégorie Snake World de Welcome m'a posé un petit soucis avec l'erreur "something is wrong with Buggle" ou un truc dans ce genre là. Il s'avère que le buggle était tout simplement mal orienté à la fin du programme (au Nord tandis que la solution devait être Est). Ce problème était cependant difficilement décelable étant donné que le buggle recouvre l'ensemble de quadrillage de rouge et qu'il est lui-même ... ROUGE eh oui ! Un petit changement de couleur pourrait s'avérer opportun.
Salutations.

_Copied from original issue: BuggleInc/webPLM#50_

**Comment by MatthieuNICOLAS** [comment]
This issue has been fixed with https://github.com/BuggleInc/webPLM/commit/777ec4c5a9e61a8496849367176f7f7ae96a8f1f, thus closing it.
