### ISSUE TITLE
Typo dans un énoncé

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/PLM#483]
Dans l'énoncé des tours de Hanoï séparées :
"Étant donné" est orthographié dans l'énoncé comme "Étant donnée"

--------------------[ Informations techniques ]--------------------
(Cela peut nous aider à résoudre votre problème, ne pas effacer SVP)

Lesson: recursion.hanoi
Exercise: recursion.hanoi.lessons.recursion.hanoi.SplitHanoi1
Programming Language: Python
Locale: français (France)
Java version: 1.8.0_141 (VM: OpenJDK 64-Bit Server VM; version: 25.141-b15)
OS: Linux (version: 4.9.0-3-amd64; arch: amd64)
PLM version: 2.7 (20170901)
Public user ID: PLM149a53604fb1ebf21bd0ce51ab8e9fb3d4e6ff0c

**Comment by jcb** [comment]
Pas certain que ce soit une typo : en fait les deux orthographes sont acceptées

**Comment by mquinson** [comment]
Effectivement, ce n'est pas un bug. On ferme, mais merci du retour.
