### ISSUE TITLE
détection sortie pas claire

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/PLM#486]
le fait de regarder la couleur du sol n'est pas mentionné (dans la mission) pour detecter si la sortie a été trouvée.

--------------------[ Informations techniques ]--------------------
(Cela peut nous aider à résoudre votre problème, ne pas effacer SVP)

Lesson: welcome
Exercise: welcome.lessons.welcome.loopdowhile.Poucet1
Programming Language: Python
Locale: français (France)
Java version: 1.8.0_131 (VM: OpenJDK 64-Bit Server VM; version: 25.131-b11)
OS: Linux (version: 4.4.0-93-generic; arch: amd64)
PLM version: 2.7 (20170901)
Public user ID: PLM09ef43188207e5fb14e5aef42dfb2c294f064d41

**Comment by mquinson** [comment]
En fait, si, c'est indiqué dans le texte de la mission...
