### ISSUE TITLE
Solve written slove

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/PLM#500]
In SplitHanoi3, one of the example is written as slove(1, 3, 0, 2) instead of solve(1, 3, 0, 2).

--------------------[ Technical Information ]--------------------
(This can help us fixing your problem, please don't erase)

Lesson: recursion.hanoi
Exercise: recursion.hanoi.lessons.recursion.hanoi.SplitHanoi3
Programming Language: Python
Locale: English (United States)
Java version: 1.8.0_144 (VM: OpenJDK 64-Bit Server VM; version: 25.144-b01)
OS: Linux (version: 4.12.8-2-ARCH; arch: amd64)
PLM version: 2.7 (20170901)
Public user ID: PLM62729fcfc7cc8cc72509811b5825b8ab59ff6526

**Comment by mquinson** [comment]
fixed previously.
