### ISSUE TITLE
fenêtre interactive

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/PLM#501]
Les tours de Hanoi interclassées
Dans la fenêtre pour faire des tests (manuellement), on ne peut avoir accès qu'aux 3 premiers piquets alors qu'il y en a 4

--------------------[ Informations techniques ]--------------------
(Cela peut nous aider à résoudre votre problème, ne pas effacer SVP)

Lesson: recursion.hanoi
Exercise: recursion.hanoi.lessons.recursion.hanoi.InterleavedHanoi
Programming Language: Python
Locale: français (France)
Java version: 1.8.0_131 (VM: OpenJDK 64-Bit Server VM; version: 25.131-b11)
OS: Linux (version: 4.4.0-93-generic; arch: amd64)
PLM version: 2.7 (20170901)
Public user ID: PLM7d8b55c1e412298be7d256b022756e6df08745cd

**Comment by mquinson** [comment]
Dupplicate of #502, thus closing.
