### ISSUE TITLE
forward(int) forbidden

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/PLM#518]
Je ne comprends le message d'erreur "forward(int) forbidden in this exercise". Le message en anglais est très claire mais je n'utilise pas de fonction nommée "forward" mais "avance".
J'utilise la fonction avance() sans paramètre...
J'ai essayé avec paramètre sans plus de succès...
Bref je suis bloqué, pourtant mon code est cohérent...
Comment suis-je censé faire bouger les buggles sans la fonction avance() à ce stade ?

--------------------[ Informations techniques ]--------------------
(Cela peut nous aider à résoudre votre problème, ne pas effacer SVP)

Lesson: welcome
Exercise: welcome.lessons.welcome.methods.args.MethodsArgs
Programming Language: Python
Locale: français (France)
Java version: 9.0.1 (VM: Java HotSpot(TM) 64-Bit Server VM; version: 9.0.1+11)
OS: Windows 10 (version: 10.0; arch: amd64)
PLM version: 2.7 (20170901)
Public user ID: PLM007d8598894e72d7b8c8cd59dfed53963a39ee0f

**Comment by mquinson** [comment]
Now fixed in the JavaUI branch, thus closing.
