### ISSUE TITLE
Disfonctionnement de avance() et recule()

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/PLM#519]
--------------------[ Informations techniques ]--------------------
(Cela peut nous aider à résoudre votre problème, ne pas effacer SVP)

Lesson: welcome
Exercise: welcome.lessons.welcome.methods.args.MethodsArgs
Programming Language: Python
Locale: français (France)
Java version: 1.8.0_151 (VM: Java HotSpot(TM) 64-Bit Server VM; version: 25.151-b12)
OS: Windows 10 (version: 10.0; arch: amd64)
PLM version: 2.7 (20170901)
Public user ID: PLMb0c7b764a1c341705fdc37e34adaace0e257feab

Les methodes avance() et recule() ne fonctionnent pas dans cette exercice bien que leur equivalent en anglais (forward() et backward()) fonctionne.
Elled sont ignorer par le programme et et le fenetre de deboguage retourne "forward(int) forbidden in this exercise" ou "backward(int) forbidden in this exercise"

Le problème est probablement causer par l'interdiction des commande forward(int) et backward(int), (c'est à dire les même commandes mais avec un nombre entier à préciser)

**Comment by mquinson** [comment]
Now fixed in javaUI branch, thus closing.
