### ISSUE TITLE
[Mac] Localization of the JavaLearningMachine menu

### ISSUE THREAD

**Issue by fstengel** [BuggleInc/PLM#85]
It seems that the locale for this menu is not the locale for the other UI items. As fars as I can ascertain the locale for this menu is provided by the system and treated as if the application was a proper mac one. As there is no OSX application bundle (and therefore no localized .nib file), the system seems to assume the language to be English...

I'll have a look at appbundler found on oracle's web site (http://docs.oracle.com/javase/7/docs/technotes/guides/jweb/packagingAppsForMac.html), but I don't hold much hope...

**Comment by mquinson** [comment]
This issue is gone with the Java Swing client, thus closing.
